"""Initial migration

Revision ID: 640bda1c318f
Revises: 
Create Date: 2025-06-09 14:51:12.007142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640bda1c318f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('weight', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_settings',
    sa.Column('user_settings_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_goal_ml', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('user_settings_id')
    )
    op.create_table('water_logs',
    sa.Column('water_logs_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_ml', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('water_logs_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_logs')
    op.drop_table('user_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
